version: '3.5'


services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: foxbase
      POSTGRES_PASSWORD: foxbaseRoot
      PGDATA: /data/postgres
    volumes:
       - ./database:/data/postgres
    ports:
      - "5432:5432"
